version: '3.5'

services: 
  nodejs: 
    image: node:8
    container_name: api
    volumes:
      - ./api:/api
    working_dir: /api
    ports:
      - 3000:3000
    command: bash -c "npm i && npm start"
